version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: estapar-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking
    ports:
      - "3306:3306"
    networks:
      - estapar-net
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: estapar-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/parking
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "3003:3003"
    networks:
      - estapar-net

  simulator:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: estapar-simulator
    network_mode: "host"
    restart: always

volumes:
  mysql_data:

networks:
  estapar-net:
